//-----------------------------------------------------------------------
// <copyright file=" advertisement.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: advertisement.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// advertisement Entity Model
    /// </summary>    
    public class advertisement: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public string image { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public string url { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public int sort { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public int is_use { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public int crate_system_user_id { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public DateTime create_date_time { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public DateTime update_date_time { get; set; }
		    }
}
