//-----------------------------------------------------------------------
// <copyright file=" category.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: category.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// category Entity Model
    /// </summary>    
    public class category: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public string name { get; set; }
		    }
}
