//-----------------------------------------------------------------------
// <copyright file=" link.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: link.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// link Entity Model
    /// </summary>    
    public class link: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public string name { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public string url { get; set; }
		    
     
				/// <summary>
        /// 创建人
        /// </summary>
        public int create_system_user { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public DateTime create_date_time { get; set; }
		    }
}
