//-----------------------------------------------------------------------
// <copyright file=" news_comment.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: news_comment.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// news_comment Entity Model
    /// </summary>    
    public class news_comment: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 文章编号
        /// </summary>
        public int news_id { get; set; }
		    
     
				/// <summary>
        /// 评论人
        /// </summary>
        public int user_id { get; set; }
		    
     
				/// <summary>
        /// 评论内容
        /// </summary>
        public string content { get; set; }
		    
     
				/// <summary>
        /// 评论时间
        /// </summary>
        public DateTime create_date_time { get; set; }
		    }
}
