//-----------------------------------------------------------------------
// <copyright file=" news.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: news.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// news Entity Model
    /// </summary>    
    public class news : BaseEntity
    {



        /// <summary>
        /// 文章类别
        /// </summary>
        public int category_id { get; set; }


        /// <summary>
        /// 标题
        /// </summary>
        public string title { get; set; }


        /// <summary>
        /// 内容
        /// </summary>
        public string content { get; set; }


        /// <summary>
        /// 阅读量
        /// </summary>
        public int number { get; set; }
        public int good_number{get;set;}

        /// <summary>
        /// 发布人
        /// </summary>
        public int user_id { get; set; }

        //[ForeignKey("user_id")]   //外键
      //  public virtual user user {get;set;}

        /// <summary>
        /// 最后修改时间
        /// </summary>
        public DateTime update_date_time { get; set; }


        /// <summary>
        /// 创建时间
        /// </summary>     
        public DateTime create_date_time { get; set; }

        public string image{get;set;}
        public string description{get;set;}
    }
}
