//-----------------------------------------------------------------------
// <copyright file=" user_simple_message_good_record.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: user_simple_message_good_record.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// user_simple_message_good_record Entity Model
    /// </summary>    
    public class user_simple_message_good_record: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public int simple_message_id { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public int user_id { get; set; }
		    
     
				/// <summary>
        /// 点赞时间
        /// </summary>
        public DateTime create_date_time { get; set; }
		    }
}
