//-----------------------------------------------------------------------
// <copyright file=" user_message.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: user_message.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// user_message Entity Model
    /// </summary>    
    public class user_message: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public int from_user_id { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public int to_user_id { get; set; }
		    
     
				/// <summary>
        /// 
        /// </summary>
        public string content { get; set; }
		    
     
				/// <summary>
        /// 留言时间
        /// </summary>
        public DateTime create_date_time { get; set; }
		    }
}
