//-----------------------------------------------------------------------
// <copyright file=" user.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: user.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// user Entity Model
    /// </summary>    
    public class user: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 真实姓名
        /// </summary>
        public string name { get; set; }
		    
     
				/// <summary>
        /// 昵称
        /// </summary>
        public string nickname { get; set; }
		    
     
				/// <summary>
        /// 头像
        /// </summary>
        public string photo { get; set; }
		    
     
				/// <summary>
        /// 手机号码
        /// </summary>
        public string phone { get; set; }
		    
     
				/// <summary>
        /// 帐号
        /// </summary>
        public string account { get; set; }
		    
     
				/// <summary>
        /// 密码
        /// </summary>
        public string password { get; set; }
		    
     
				/// <summary>
        /// 主站点
        /// </summary>
        public string index { get; set; }
		    
     
				/// <summary>
        /// 微信二维码
        /// </summary>
        public string wechat_image { get; set; }
		    
     
				/// <summary>
        /// 注册时间
        /// </summary>
        public DateTime create_date_time { get; set; }
		    }
}
