//-----------------------------------------------------------------------
// <copyright file=" user_simple_message.cs" company="四川易迅通健康医疗有限公司 Enterprises">
// * Copyright (C) 2018 四川易迅通健康医疗有限公司 Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: user_simple_message.cs
// * history : Created by T4 04/25/2018 19:31:41 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace SkyBlog.Models.DbModel
{
    /// <summary>
    /// user_simple_message Entity Model
    /// </summary>    
    public class user_simple_message: BaseEntity
    {
    
	    
     
				/// <summary>
        /// 
        /// </summary>
        public int user_id { get; set; }
		    
     
				/// <summary>
        /// 说说内容
        /// </summary>
        public string message { get; set; }
		    
     
				/// <summary>
        /// 图片
        /// </summary>
        public string image { get; set; }
		    
     
				/// <summary>
        /// 赞
        /// </summary>
        public int good { get; set; }
		    }
}
